### ISSUE TITLE
请问录制的dm3弹幕文件如何二次编辑

### ISSUE THREAD

**Issue by tiancailin** [WhiteMinds/LiveAutoRecord#20]
用sublime打开后发现是个二进制文件，录制的是斗鱼
希望能有方法转化为.srt或其他主流字幕格式
望赐教

**Comment by WhiteMinds** [comment]
实际上是 sqlite 文件，你可以写个脚本，从 sqlite 提取数据转成 srt

我本身是想做这个功能的，但是一直没时间更新，短期内应该也没什么时间

**Comment by Heporis** [comment]
> 实际上是 sqlite 文件，你可以写个脚本，从 sqlite 提取数据转成 srt
> 
> 我本身是想做这个功能的，但是一直没时间更新，短期内应该也没什么时间

能不能把弹幕和视频给封装到一起，然后录制完了自动上传B站😁
比如这两个，但是它们不支持斗鱼https://github.com/Bililive/BililiveRecorder和https://github.com/valkjsaaa/auto-bilibili-recorder
这个支持斗鱼但是不能录制弹幕https://github.com/ForgQi/biliup🤣

**Comment by Heporis** [comment]
> 实际上是 sqlite 文件，你可以写个脚本，从 sqlite 提取数据转成 srt
> 
> 我本身是想做这个功能的，但是一直没时间更新，短期内应该也没什么时间

能不能把弹幕和视频给封装到一起，然后录制完了自动上传B站😁
比如这两个，但是它们不支持斗鱼https://github.com/Bililive/BililiveRecorder
和https://github.com/valkjsaaa/auto-bilibili-recorder
这个支持斗鱼但是不能录制弹幕https://github.com/ForgQi/biliup🤣

**Comment by WhiteMinds** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    我想做的就是这个，不过没什么时间搞
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                whitemind
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2022年01月9日 ***@***.***> 写道： 






实际上是 sqlite 文件，你可以写个脚本，从 sqlite 提取数据转成 srt

我本身是想做这个功能的，但是一直没时间更新，短期内应该也没什么时间



能不能把弹幕和视频给封装到一起，然后录制完了自动上传B站😁

比如这两个，但是它们不支持斗鱼https://github.com/Bililive/BililiveRecorder

和https://github.com/valkjsaaa/auto-bilibili-recorder

这个支持斗鱼但是不能录制弹幕https://github.com/ForgQi/biliup🤣



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you commented.Message ID: ***@***.***>

**Comment by Heporis** [comment]
> 实际上是 sqlite 文件，你可以写个脚本，从 sqlite 提取数据转成 srt
> 
> 我本身是想做这个功能的，但是一直没时间更新，短期内应该也没什么时间

如果有时间做的话，希望能做个用docker跑在云服务器上😁

**Comment by WhiteMinds** [comment]
> > 实际上是 sqlite 文件，你可以写个脚本，从 sqlite 提取数据转成 srt
> > 我本身是想做这个功能的，但是一直没时间更新，短期内应该也没什么时间
> 
> 如果有时间做的话，希望能做个用docker跑在云服务器上😁

4.x 现在支持服务端部署、模块引入，然后弹幕不再使用 dm3，而是 json，并且支持 srt 导出。
